### PR TITLE
Adding additional features, admin functionality and full integration with IRIS IAM group membership scheme

### PR DESCRIPTION
**Pull request by sam-glendenning**
Major update to tie in with release of IRIS DynaFed service.

- oidc_auth.py - the authorisation plugin itself. Making minor tweaks to accommodate changes in structure of oidc_auth.json file
- manage_oidc_json.py - adds, amends and deletes bucket config files based on user activity with importing and removing buckets on web UI. Also validates oidc_auth.json
- sync.py - responsible for synchronising local bucket config files with master copy inside iris-dynafed-config Echo bucket. This allows for multiple DynaFed hosts behind a loadbalancer to have the same bucket config data
- import.py - receives info about bucket the user wants to import from the web UI via a POST request. Lives in /var/www/cgi-bin on the host and calls the import function from manage_oidc_json.py
- remove.py - receives info about bucket the user wants to import from the web UI via a POST request. Lives in /var/www/cgi-bin on the host and calls the remove function from manage_oidc_json.py
- oidc_auth.json - template that is added to with new authorisation rules by manage_oidc_auth.json when buckets are imported and removed. Lives in /etc/grid-security/ on the host

### CODE REVIEW

**Comment by sam-glendenning** [comment]
Added admin functionality. This allows for requests from admins to be received from the front-end portal for tasks such as viewing and amending the blacklist, importing and removing buckets from any group and accessing any bucket in the system. 

An additional blacklist.json file is now maintained (not in this repo but created and managed by the files) and synchronised with the Echo bucket upstream along with the other .conf files. This allows for global blocking of accessing to admin-specified buckets. The list can be amended by admins at any time.

Slightly altered requests are received from the front-end if an admin is importing/removing a bucket. Scripts have been amended to account for this and allow admins to bypass a couple of checks relating to bucket keys and verification in order to gain elevated privileges.

**Comment by sam-glendenning** [comment]
@norealroots I have invited you as a collaborator to this repo so you should be able to add yourself as a reviewer to this PR once you've accepted the invite

**Comment by sam-glendenning** [comment]
@louise-davies as above with Tom

**Review by norealroots — APPROVED** [review]

**Review by norealroots — APPROVED** [review]
This looks to be a well documented and thought through upgrade to the previous work done by both @louise-davies and myself. An excellent piece of work.

**Review by norealroots — COMMENTED** [review]
This seems to make reference to your S3 account specificially @sam-glendenning - how easy would it be for this to updated and changed should:

- your S3 account need to be deleted for any reason?
- another organisation/site want to utilise this tool?

**Comment by sam-glendenning** [comment]
> This seems to make reference to your S3 account specificially @sam-glendenning - how easy would it be for this to updated and changed should:
> 
> * your S3 account need to be deleted for any reason?
> * another organisation/site want to utilise this tool?

The file in question is called config-bucket-credentials.json. It comes in the format:
`{
	"s3-access-key": "XXXX",
	"s3-secret-key": "XXXXXXXXX"
}`
This makes it very easy for the JSON values to be changed as necessary. If the account being used were to change, these values need only be changed.

In light of this question, however, I've decided to make it easier to change these settings. I will add a further commit whereby the name of the bucket to synchronise with will also go in this JSON file, instead of being hard coded in sync.py.

**Review by norealroots — APPROVED** [review]
Good change - makes it easy to manage and less IRIS-specific.

**Review by norealroots — APPROVED** [review]

**Pull request merged**
